### ISSUE TITLE
Impossible to push!

### ISSUE THREAD

**Issue by ncarboni** [ilokhov/picasso#1]
Hola!
I tried to upload the CSV but I got the following error:

> Pushing to https://github.com/ilokhov/picasso
> remote: Permission to ilokhov/picasso.git denied to ncarboni.
> fatal: unable to access 'https://github.com/ilokhov/picasso/': The requested URL returned error: 403

**Comment by ilokhov** [comment]
Hey Nicola!

You are trying to push directly to the master branch. Please do a pull request from your branch with the CSV file and I can then merge it into the master branch. Thanks!
